"""initial

Revision ID: 71cfcbfae558
Revises: 
Create Date: 2026-02-25 00:03:08.111317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71cfcbfae558'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sqlite_sequence')
    op.drop_constraint(None, 'forum_participants', type_='foreignkey')
    op.drop_constraint(None, 'forum_participants', type_='foreignkey')
    op.create_foreign_key(None, 'forum_participants', 'personas', ['persona_id'], ['id'])
    op.create_foreign_key(None, 'forum_participants', 'forums', ['forum_id'], ['id'])
    op.drop_index('idx_forums_creator', table_name='forums')
    op.create_index(op.f('ix_forums_id'), 'forums', ['id'], unique=False)
    op.drop_constraint(None, 'forums', type_='foreignkey')
    op.create_foreign_key(None, 'forums', 'users', ['creator_id'], ['id'])
    op.create_index(op.f('ix_god_logs_id'), 'god_logs', ['id'], unique=False)
    op.drop_constraint(None, 'god_logs', type_='foreignkey')
    op.create_foreign_key(None, 'god_logs', 'users', ['god_user_id'], ['id'])
    op.drop_index('idx_messages_forum', table_name='messages')
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'forums', ['forum_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'personas', ['persona_id'], ['id'])
    op.drop_index('idx_observations_user_forum', table_name='observations')
    op.create_index(op.f('ix_observations_id'), 'observations', ['id'], unique=False)
    op.drop_constraint(None, 'observations', type_='foreignkey')
    op.drop_constraint(None, 'observations', type_='foreignkey')
    op.create_foreign_key(None, 'observations', 'forums', ['forum_id'], ['id'])
    op.create_foreign_key(None, 'observations', 'users', ['user_id'], ['id'])
    op.drop_index('idx_personas_owner', table_name='personas')
    op.create_index(op.f('ix_personas_id'), 'personas', ['id'], unique=False)
    op.drop_constraint(None, 'personas', type_='foreignkey')
    op.create_foreign_key(None, 'personas', 'users', ['owner_id'], ['id'])
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_constraint(None, 'personas', type_='foreignkey')
    op.create_foreign_key(None, 'personas', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_personas_id'), table_name='personas')
    op.create_index('idx_personas_owner', 'personas', ['owner_id'], unique=False)
    op.drop_constraint(None, 'observations', type_='foreignkey')
    op.drop_constraint(None, 'observations', type_='foreignkey')
    op.create_foreign_key(None, 'observations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'observations', 'forums', ['forum_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_observations_id'), table_name='observations')
    op.create_index('idx_observations_user_forum', 'observations', ['user_id', 'forum_id'], unique=False)
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'personas', ['persona_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'messages', 'forums', ['forum_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.create_index('idx_messages_forum', 'messages', ['forum_id'], unique=False)
    op.drop_constraint(None, 'god_logs', type_='foreignkey')
    op.create_foreign_key(None, 'god_logs', 'users', ['god_user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_god_logs_id'), table_name='god_logs')
    op.drop_constraint(None, 'forums', type_='foreignkey')
    op.create_foreign_key(None, 'forums', 'users', ['creator_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_forums_id'), table_name='forums')
    op.create_index('idx_forums_creator', 'forums', ['creator_id'], unique=False)
    op.drop_constraint(None, 'forum_participants', type_='foreignkey')
    op.drop_constraint(None, 'forum_participants', type_='foreignkey')
    op.create_foreign_key(None, 'forum_participants', 'forums', ['forum_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'forum_participants', 'personas', ['persona_id'], ['id'], ondelete='CASCADE')
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    # ### end Alembic commands ###
